services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "8080:80"
    depends_on:
      - pocketbase
    restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    command: --dir=/pb_data
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_data/pb_hooks
    ports:
      - "8092:8090"
    restart: unless-stopped
