import type { CrossedSignalsPuzzle } from './crossedSignalsPuzzles';

// Generated by scripts/generate_crossed_signals_puzzles.ts.
// Keep this file committed so the app can import it before any generated packs exist.
export const CROSSED_SIGNALS_GENERATED_PUZZLES: CrossedSignalsPuzzle[] = [];
